import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.scss";
import BootstrapClient from "./components/BootstrapClient";

export const metadata = {
  title: "Shakil Ansary",
  description: "Generated by create next app",
  icons: {
    icon: "/images/favicon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <BootstrapClient />
      </body>
    </html>
  );
}
